os: linux
dist: xenial

language: cpp
compiler: clang

addons:
  apt:
    sources:
      - llvm-toolchain-xenial-8
      - ubuntu-toolchain-r-test
    packages:
      - clang++-8
      - libc++-8-dev
      - libc++abi-8-dev
      - clang-tidy-8

before_install:
  - chmod +x build.sh
  - chmod +x tidy.sh

script:
  - export CXX=/usr/bin/clang++-8
  - $CXX --version
  - clang-tidy-8 --version
  - bash ./build.sh
  - bash ./tidy.sh
