os: linux
dist: xenial
language: cpp

matrix:
  fast_finish: true
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
            - ubuntu-toolchain-r-test
          packages:
            - clang++-8
            - libc++-8-dev
            - libc++abi-8-dev
            - clang-tidy-8
      env:
        - MATRIX_EVAL="export CXX=/usr/bin/clang++-8 && export CLANG_TIDY=/usr/bin/clang-tidy-8 && export STDLIB=-stdlib=libc++"
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
            - llvm-toolchain-xenial-7
            - ubuntu-toolchain-r-test
          packages:
            - clang++-7
            - libc++-7-dev
            - libc++abi-7-dev
      env:
        - MATRIX_EVAL="export CXX=/usr/bin/clang++-7 && export STDLIB=-stdlib=libc++"
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
            - ubuntu-toolchain-r-test
          packages:
            - clang++-6.0
            - libc++-dev
            - clang-tidy-6.0
      env:
        - MATRIX_EVAL="export CXX=/usr/bin/clang++-6.0 && export CLANG_TIDY=/usr/bin/clang-tidy-6.0 && export STDLIB=-stdlib=libc++"
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="export CXX=/usr/bin/g++-8 && export STDLIB=''"
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="export CXX=/usr/bin/g++-7 && export STDLIB=''"
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="export CXX=/usr/bin/g++-6 && export STDLIB=''"
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="export CXX=/usr/bin/g++-5 && export STDLIB=''"

before_install:
  - chmod +x build.bash
  - chmod +x tidy.bash
  - eval "${MATRIX_EVAL}"

script:
  - ./build.bash
  - ./tidy.bash
